# 자동차 종류 '세단' OR 'SUV'
# 2022-11-01 ~ 2022-11-30 대여 가능
# 대여 금액 : 50만원 이상 200만원 미만

SELECT A.CAR_ID, A.CAR_TYPE, ROUND(30*A.DAILY_FEE*(100-C.DISCOUNT_RATE)*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A 
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV') AND
        C.DURATION_TYPE LIKE '%30일%'
GROUP BY A.CAR_ID
HAVING MAX(B.END_DATE) < '2022-11-01' AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC