SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.TOTAL_AMOUNT) AS TOTAL_SALES
FROM (SELECT *, SUM(AMOUNT) AS TOTAL_AMOUNT
     FROM FOOD_ORDER
     WHERE PRODUCE_DATE LIKE '2022-05-%'
     GROUP BY PRODUCT_ID) AS O JOIN FOOD_PRODUCT AS P USING(PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC