WITH RECURSIVE CTE(N) AS
(
    SELECT 0
    UNION ALL
    SELECT N+1 FROM CTE WHERE N < 23
)

SELECT N AS HOUR, COUNT(ANIMAL_ID)
FROM CTE LEFT JOIN ANIMAL_OUTS ON N = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR