# 세단, 10월대여, 자동차 ID리스트 출력, 중복없이, 자동차ID 기준 내림차순
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단' AND B.START_DATE LIKE '%-10-%'
ORDER BY A.CAR_ID DESC